### ISSUE TITLE
last update

### ISSUE THREAD

**Issue by fendi1989** [mgeeky/RedWarden#8]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/home/RedWarden/lib/proxyhandler.py", line 1173, in get
    self.my_handle_request()
  File "/home/RedWarden/lib/proxyhandler.py", line 325, in my_handle_request
    if self.options['access_log_format'].lower() == 'apache2':
AttributeError: 'NoneType' object has no attribute 'lower'

this error appears each time the server gets hit by a request since the last update. no weblog on cobalt strike's console, so I assume redwarden still do its job correctly.

**Comment by mgeeky** [comment]
Dammit, expect a fix in a few minutes!

**Comment by mgeeky** [comment]
Hi,

Hopefully the last commit [397e516](https://github.com/mgeeky/RedWarden/commit/397e516eec53ddd8dc6c5520bbc702fb4e8ac0a2) addressed your issue. Sorry for this nuissance.

Can you please let me know if it works now as expected?

Kind regards,
Mariusz.
